### ISSUE TITLE
问一下, P29页的例3.59的命令是什么意思呢?

### ISSUE THREAD

**Issue by ningliu2024** [wanmuc/BackEnd#1]
```shell
cat /etc/init.d/sshd  |  grep -v '^#'  |  grep -v '^$'  .  /etc/rc.d/init.d/functions
```

**Comment by wanmuc** [comment]
抱歉，不经常登录github，现在才看到你的问题。

你的理解错了，3.59的命令是**cat /etc/init.d/sshd  |  grep -v '^#'  |  grep -v '^$'**，而不是**cat /etc/init.d/sshd  |  grep -v '^#'  |  grep -v '^$'  .  /etc/rc.d/init.d/functions**

**grep -v '^#'** 用于过滤掉#开头的内容。 **grep -v '^$'**  用于过滤掉空行。

所以**cat /etc/init.d/sshd  |  grep -v '^#'  |  grep -v '^$'** 命令就是用于过滤掉/etc/init.d/sshd文件中#开头的内容和空行，并把最后的内容显示在终端。

**Comment by ningliu2024** [comment]
OK, 谢谢了

**Comment by wanmuc** [comment]
阅读过程中，有任何问题都可以在这里提问，你们的反馈非常重要。也可以关注我微信公众号，加入技术交流群，一起讨论问题。
